name: my_drive
description: Store and view your personal files on a personal cloud server
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: ^3.0.9
  path_provider: ^1.6.8
  percent_indicator: ^2.1.1
  file_picker: ^1.5.0+2
  flutter_plugin_pdf_viewer: ^1.0.7

flutter:
  uses-material-design: true
